name: Build and Package

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Homebrew
        run: |
          brew update
          brew install create-dmg

      - name: Build App
        run: |
          xcodebuild -scheme "Dump1090 macOS GUI" \
                     -configuration Release \
                     -destination "platform=macOS" \
                     BUILD_DIR=build \
                     clean build

      - name: Package DMG
        run: |
          create-dmg \
            --volname "Dump1090MAC" \
            --window-pos 200 120 \
            --window-size 600 400 \
            --icon-size 128 \
            --icon "Dump1090 macOS GUI.app" 150 150 \
            --hide-extension "Dump1090 macOS GUI.app" \
            --app-drop-link 450 450 \
            "build/Release/Dump1090MAC.dmg" \
            "build/Release/Dump1090 macOS GUI.app"

      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: Dump1090MAC-DMG
          path: build/Release/Dump1090MAC.dmg
